# Configuração do Servidor Web
server.port=8081

# Nome da Aplicação
spring.application.name=escala-api

# Configuração de Conexão com PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/escala_transito_db
spring.datasource.username=postgres
spring.datasource.password=Gomes9914
spring.datasource.driver-class-name=org.postgresql.Driver

# Configuração do JPA / Hibernate
# 'update': Cria/altera o esquema do banco automaticamente baseado nas classes Java.
# Ideal para dev, mas perigoso em produção (usaremos Flyway/Liquibase no futuro).
spring.jpa.hibernate.ddl-auto=update

# Configurações de Log (Visualizar o SQL gerado no console)
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Dialeto (O Hibernate geralmente detecta, mas é bom explicitar para evitar warnings)
#spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Segredo para assinar o JWT (em produção, isso deve ser uma variável de ambiente)
api.security.token.secret=123456789-senha-super-secreta-da-escala