# Configuração do Servidor Web
server.port=8081

# Nome da Aplicação
spring.application.name=escala-api

# Configuração de Conexão com PostgreSQL
spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/escala_transito_db}
spring.datasource.username=${DB_USER:postgres}
spring.datasource.password=${DB_PASSWORD:G1240@Ap}
spring.datasource.driver-class-name=org.postgresql.Driver

# Configuração do JPA / Hibernate
# 'update': Cria/altera o esquema do banco automaticamente baseado nas classes Java.
# Ideal para dev, mas perigoso em produção (usaremos Flyway/Liquibase no futuro).
spring.jpa.hibernate.ddl-auto=update

# Configurações de Log (Visualizar o SQL gerado no console)
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Dialeto (O Hibernate geralmente detecta, mas é bom explicitar para evitar warnings)
#spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Segredo para assinar o JWT (escondido na nuvem, padrão no local)
api.security.token.secret=${JWT_SECRET:123456789-senha-super-secreta-da-escala}